spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userdb?autoReconnect=true&allPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
